# Important Steps

a = 1
print (a)

Agenda for the Notebook

- Enviornment Setup using Anaconda
- Python Data Structure 
  - List 
  - Tuples
  - Set
  - Dictionary 
  - Strings
- Functions
- Numpy Array 
- Pandas 


Google Collab Users:
    - No need to setup environment
    
Windows/Mac Desktop 
(* You should have anaconda installed and should have Anaconda Prompt/terminal running) 

- conda create -n mlbootcamp python=3


Some important installations to be done before starting:
- pandas
- scikit-learn 
- matplotlib 
- seaborn 
- plotly-epxress

# List

-> List is one of the Sequence Data structure

-> Lists are collection of items (Strings, integers or even other lists)

-> Lists are enclosed in [ ]

-> Each item in the list has an assigned index value.

-> Each item in a list is separated by a comma

-> Lists are mutable, which means their value can be changed.

In [78]:
a = 1  # variable 

In [79]:
print (a)

1


In [80]:
print ("My name is Lavi")  # string in python has to be with quotes 

My name is Lavi


In [90]:
print ("my name is lavi")

SyntaxError: invalid syntax (<ipython-input-90-f0d0af76d9fe>, line 1)

In [81]:
4+5

9

## List Operations

In [82]:
# Creating a List 

emptyList = []

lst = ['one', 'two', 'three', 'four'] # list of strings

lst2 = [1, 2, 3, 4] #list of integers

lst3 = [[1, 2], [3, 4]] # list of lists

lst4 = [1, 'mark', 24, 1.24] # list of different datatypes

print(lst4)

[1, 'mark', 24, 1.24]


In [91]:
l1 = ["name","address",1,3.4]   # 1 digits -> integers.  # 2.095 float 
        0       1      2  3 

In [85]:
print(l)

['name', 'address', 1, 3.4]


In [96]:
l1[-2]

1

In [11]:
# Accesing List Elements 

lst = [1, 2, 3, 4]
print(lst[1]) #print second element

#print last element using negative index
print(lst[-2])

2
3


In [12]:
# Accesing multiple Elements using List Slicing 

numbers = [10, 20, 30, 40, 50,60,70,80]

#print all numbers
print(numbers[:]) 

#print from index 0 to index 3
print(numbers[0:4])

print (numbers)
#print alternate elements in a list
print(numbers[::2])


#print elemnts start from 0 through rest of the list
print(numbers[2::2])


[10, 20, 30, 40, 50, 60, 70, 80]
[10, 20, 30, 40]
[10, 20, 30, 40, 50, 60, 70, 80]
[10, 30, 50, 70]
[30, 50, 70]


In [98]:
numbers = [10, 20, 30, 40, 50,60,70,80]
numbers[0:5]

[10, 20, 30, 40, 50]

In [99]:
# Finding length of List 


lst = ['one', 'two', 'three', 'four']

#find length of a list
print(len(lst))

4


In [101]:
type(lst[0])

str

In [89]:
# Appending new elements to list at last index position 


lst = ['one', 'two', 'three', 'four']

lst.append(1) # append will add the item at the end

print(lst)

['one', 'two', 'three', 'four', 1]


In [4]:
# Adding new element at specific Index

#syntax: lst.insert(x, y) 

lst = ['one', 'two', 'four']

lst.insert(2, "three") # will add element y at location x

print(lst)


['one', 'two', 'three', 'four']


In [6]:
# Removing the element

#syntax: lst.remove(x) 

lst = ['one', 'two', 'three', 'four', 'two']

lst.remove('two') #it will remove first occurence of 'two' in a given list

print(lst)

['one', 'three', 'four', 'two']


In [ ]:
lst.pop()

In [7]:
# Extending the elements 

lst = ['one', 'two', 'three', 'four']

lst2 = ['five', 'six']

#extend will join the list with list1

lst.extend(lst2)

print(lst)

['one', 'two', 'three', 'four', 'five', 'six']


In [103]:
# Conditional Statements in List 

#keyword 'in' is used to test if an item is in a list
lst = ['one', 'two', 'three', 'four']

if 'two' in lst:
    
    print('found the value')

found the value


In [109]:
#keyword 'not' can combined with 'in'
if 'six' in lst:
    print('Element found')
# elif 'three' in lst:
#     print ("Element found")
# else:
#     print ("Element not found")
    

In [110]:
# Sorting the list through sorted global python function 

#create a list with numbers
numbers = [3, 1, 6, 2, 8]

sorted_lst = sorted(numbers,reverse=False)


print("Sorted list :", sorted_lst)

#original list remain unchanged
print("Original list: ", numbers)

Sorted list : [1, 2, 3, 6, 8]
Original list:  [3, 1, 6, 2, 8]


In [111]:
# List method to sort the elements. Doesn't work in mixed type datastype scenario. Only on Int and FLoats

lst = [1, 20, 5, 5, 4.2]

#sort the list and stored in itself
lst.sort()

# add element 'a' to the list to show an error

print("Sorted list: ", lst)

Sorted list:  [1, 4.2, 5, 5, 20]


In [113]:
# Counting List Elements 
numbers = [1, 2, 3, 1, 3, 4, 2, 5,"ds","ds"]

#frequency of 1 in a list
print(numbers.count(1))

#frequency of 3 in a list
print(numbers.count(3))

print(numbers.count("ds"))

2
2
2


In [120]:
ls = [1,3,4,5,6]

ls2 = []

for eachElement in ls:
    if eachElement > 4:
        ls2.append(eachElement + 2)

In [121]:
ls2

[7, 8]

In [14]:
# using FOR loop in Lists to access values with iterator 

lst = ['one', 'two', 'three', 'four']

for ele in lst:
    print(ele)

one
two
three
four


In [122]:
# List Comprehensions
lst = [-10, -20, 10, 20, 50]

#create a new list with values doubled
new_lst = [eachElement+2 for  in lst]
print(new_lst)

[-8, -18, 12, 22, 52]


In [15]:


#filter the list to exclude negative numbers
new_lst = [i+2 for i in lst if i >= 0]
print(new_lst)


#create a list of tuples like (number, square_of_number)
new_lst = [(i, i**2) for i in range(10)]
print(new_lst)

[-20, -40, 20, 40, 100]
[10, 20, 50]
[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25), (6, 36), (7, 49), (8, 64), (9, 81)]


# Tuples

-> A tuple is similar to list

-> The diffence between the two is that we can't change the elements of tuple once it is assigned whereas in the list, elements can be changed

In [17]:
#empty tuple
t = ()

#tuple having integers
t = (1, 2, 3)
print(t)

#tuple with mixed datatypes
t = (1, 'mike', 28, 'abc')
print(t)

#nested tuple
t = (1, (2, 3, 4), [1, 'brian', 28, 'abc'])
print(t)

(1, 2, 3)
(1, 'mike', 28, 'abc')
(1, (2, 3, 4), [1, 'brian', 28, 'abc'])


In [18]:
t = ('India', 'USA', 'France', 'Germany', 'Japan')

print(t[1])

USA


In [19]:
#negative index
print(t[-1]) #print last element in a tuple

Japan


In [20]:
#nested tuple
t = ('ABC', ('USA', 'Germany', 'Japan'))

print(t[1])

('USA', 'Germany', 'Japan')


In [21]:
#Slicing
t = (1, 2, 3, 4, 5, 6)

print(t[1:4])

#print elements from starting to 2nd last elements
print(t[:-2])

#print elements from starting to end
print(t[:])

(2, 3, 4)
(1, 2, 3, 4)
(1, 2, 3, 4, 5, 6)


In [123]:
#creating tuple
t = [1, 2, 3, 4, [5, 6, 7]]

t[0] = 'x'

In [124]:
t

['x', 2, 3, 4, [5, 6, 7]]

In [125]:
#creating tuple
t1 = (1, 2, 3, 4, [5, 6, 7])

t1[0] = 'x' #will get TypeError

TypeError: 'tuple' object does not support item assignment

In [126]:
t = (1,2,(3,4,5),7)

In [128]:
t[2][1]

4

# Sets

-> A set is an unordered collection of items. Every element is unique (no duplicates).

-> The set itself is mutable. We can add or remove items from it.

-> Sets can be used to perform mathematical set operations like union, intersection, symmetric difference etc.

In [23]:
#set of integers
s = {1, 2, 3}
print(s)

#print type of s 
print(type(s))

{1, 2, 3}
<class 'set'>


In [24]:
#set doesn't allow duplicates. They store only one instance.
s = {1, 2, 3, 1, 4}
print(s)

{1, 2, 3, 4}


In [25]:
#we can make set from a list
s = set([1, 2, 3, 1])
print(s)

{1, 2, 3}


In [26]:
#we can add single element using add() method and 
#add multiple elements using update() method
s = {1, 3}
#add element
s.add(2)
print(s)

{1, 2, 3}


In [27]:
#A particular item can be removed from set using methods, 
#discard() and remove().

s = {1, 2, 3, 5, 4}
print(s)

s.discard(4)    #4 is removed from set s

print(s)

{1, 2, 3, 4, 5}
{1, 2, 3, 5}


In [28]:
set1 = {1, 2, 3, 4, 5}
set2 = {3, 4, 5, 6, 7}

#union of 2 sets using | operator

print(set1 | set2)

{1, 2, 3, 4, 5, 6, 7}


In [29]:
#another way of getting union of 2 sets
print(set1.union(set2))

{1, 2, 3, 4, 5, 6, 7}


In [30]:
#intersection of 2 sets using & operator
print(set1 & set2)

{3, 4, 5}


In [31]:
#use intersection function 
print(set1.intersection(set2))

{3, 4, 5}


In [32]:
#use differnce function 
print(set1.difference(set2))

{1, 2}


# Dictionary 
Python dictionary is an unordered collection of items. While other compound data types have only value as an element, a dictionary has a key: value pair.

In [ ]:
("key":Value)
("name":"lavi")
("session":"intro to ds")

In [ ]:
{
    key : value 
}

# 1 : [1,2,3,4]
1 : "Lavi"
    
    
EmployeeCode : Value 

In [33]:
#empty dictionary
my_dict = {}

#dictionary with integer keys
my_dict = {1: 'abc', 2: 'xyz'}
print(my_dict)

#dictionary with mixed keys
my_dict = {'name': 'satish', 1: ['abc', 'xyz']}
print(my_dict)


#create empty dictionary using dict()
my_dict = dict()

my_dict = dict([(1, 'abc'), (2, 'xyz')])    #create a dict with list of tuples
print(my_dict)

{1: 'abc', 2: 'xyz'}
{'name': 'satish', 1: ['abc', 'xyz']}
{1: 'abc', 2: 'xyz'}


In [129]:
my_dict = {'name': 'satish', 'age': 27, 'address': 'guntur'}

#get name
print(my_dict['name'])

satish


In [130]:
my_dict.keys()

dict_keys(['name', 'age', 'address'])

In [131]:
my_dict.values()

dict_values(['satish', 27, 'guntur'])

In [35]:
#another way of accessing key
print(my_dict.get('address'))

guntur


In [36]:
my_dict = {'name': 'satish', 'age': 27, 'address': 'guntur'}

#update name 
my_dict['name'] = 'raju'

print(my_dict)

{'name': 'raju', 'age': 27, 'address': 'guntur'}


In [37]:
#create a dictionary
my_dict = {'name': 'satish', 'age': 27, 'address': 'guntur'}

#remove a particular item
print(my_dict.pop('age'))

print(my_dict)

iterrows 

27
{'name': 'satish', 'address': 'guntur'}


# Strings

In [38]:
myString = 'Hello'

print(myString)


myString = "Hello"
print(myString)


myString = '''Hello'''
print(myString)

Hello
Hello
Hello


In [39]:
myString = "Hello"

#print first Character
print(myString[0])

#print last character using negative indexing
print(myString[-1])

#slicing 2nd to 5th character
print(myString[2:5])

H
o
llo


In [40]:
myString = "Hello"
myString[4] = 's' # strings are immutable

TypeError: 'str' object does not support item assignment

In [41]:
s1 = "Hello "
s2 = "Satish"

#concatenation of 2 strings
print(s1 + s2)

#repeat string n times
print(s1 * 3)

Hello Satish
Hello Hello Hello 


In [132]:
for eachcharacter in "Hello World":
    if eachcharacter == "o":
        print ("Found O")
    else:
        print ("O not found")
    

O not found
O not found
O not found
O not found
Found O
O not found
O not found
Found O
O not found
O not found
O not found


In [42]:
count = 0
for l in "Hello World":
    if l == 'o':
        count += 1
print(count, ' letters found')

2  letters found


In [43]:
print('l' in 'Hello World') #in operator to test membership

True


In [44]:
print('or' in 'Hello World')

True


In [45]:
"Hello".lower()

'hello'

In [46]:
"Hello".upper()

'HELLO'

In [47]:
"This will split all words in a list".split()

['This', 'will', 'split', 'all', 'words', 'in', 'a', 'list']

In [48]:
' '.join(['This', 'will', 'split', 'all', 'words', 'in', 'a', 'list'])

'This will split all words in a list'

# Simple Function

In [134]:
st1 = "first"
str2 = "second"

# function
def add_string(string):
    return string + " string"

In [136]:
add_string("Kishore")

'Kishore string'

In [49]:
s1 = "Bad morning"

s2 = s1.replace("Bad", "Good")

print(s1)
print(s2)

Bad morning
Good morning


In [50]:
def print_name(name):
    """ 
    This function prints the name
    """
    print("Hello " + str(name))
    

In [51]:
print_name("John")

Hello John


In [140]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print("the value is -> ",x, " and it's sign is ",sign(x))

the value is ->  -1  and it's sign is  negative
the value is ->  0  and it's sign is  zero
the value is ->  1  and it's sign is  positive


# Numpy Array 

In [141]:

ls = [1,2,3,4,
 3,4,5,6,
 6,4,6,8] 


In [142]:
ls

[1, 2, 3, 4, 3, 4, 5, 6, 6, 4, 6, 8]

In [53]:
import numpy as np  # alias or object 

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [143]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [54]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [150]:
!pip install pandas
!pip install numpy

# Pandas 

In [145]:
data = {
    'apples': [3, 2, 0, 1], 
    'oranges': [0, 3, 7, 2]
}

In [146]:
import pandas as pd

In [147]:
purchases = pd.DataFrame(data)

purchases

apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [59]:
purchases = pd.DataFrame(data, index=['June', 'Robert', 'Lily', 'David'])

purchases

apples  oranges
June         3        0
Robert       2        3
Lily         0        7
David        1        2

In [60]:
purchases.loc['June']

apples     3
oranges    0
Name: June, dtype: int64

In [148]:
movies_df = pd.read_csv("IMDB-Movie-Data.csv", index_col="Title")

In [152]:
movies_df.head()

Rank                     Genre  \
Title                                                     
Guardians of the Galaxy     1   Action,Adventure,Sci-Fi   
Prometheus                  2  Adventure,Mystery,Sci-Fi   
Split                       3           Horror,Thriller   
Sing                        4   Animation,Comedy,Family   
Suicide Squad               5  Action,Adventure,Fantasy   

                                                               Description  \
Title                                                                        
Guardians of the Galaxy  A group of intergalactic criminals are forced ...   
Prometheus               Following clues to the origin of mankind, a te...   
Split                    Three girls are kidnapped by a man with a diag...   
Sing                     In a city of humanoid animals, a hustling thea...   
Suicide Squad            A secret government agency recruits some of th...   

                                     Director  \
Title                                           
Guardians of the Galaxy            James Gunn   
Prometheus                       Ridley Scott   
Split                      M. Night Shyamalan   
Sing                     Christophe Lourdelet   
Suicide Squad                      David Ayer   

                                                                    Actors  \
Title                                                                        
Guardians of the Galaxy  Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...   
Prometheus               Noomi Rapace, Logan Marshall-Green, Michael Fa...   
Split                    James McAvoy, Anya Taylor-Joy, Haley Lu Richar...   
Sing                     Matthew McConaughey,Reese Witherspoon, Seth Ma...   
Suicide Squad            Will Smith, Jared Leto, Margot Robbie, Viola D...   

                         Year  Runtime (Minutes)  Rating   Votes  \
Title                                                              
Guardians of the Galaxy  2014                121     8.1  757074   
Prometheus               2012                124     7.0  485820   
Split                    2016                117     7.3  157606   
Sing                     2016                108     7.2   60545   
Suicide Squad            2016                123     6.2  393727   

                         Revenue (Millions)  Metascore  
Title                                                   
Guardians of the Galaxy              333.13       76.0  
Prometheus                           126.46       65.0  
Split                                138.12       62.0  
Sing                                 270.32       59.0  
Suicide Squad                        325.02       40.0

In [154]:
movies_df.tail(2)

Rank                  Genre  \
Title                                       
Search Party   999       Adventure,Comedy   
Nine Lives    1000  Comedy,Family,Fantasy   

                                                    Description  \
Title                                                             
Search Party  A pair of friends embark on a mission to reuni...   
Nine Lives    A stuffy businessman finds himself trapped ins...   

                      Director  \
Title                            
Search Party    Scot Armstrong   
Nine Lives    Barry Sonnenfeld   

                                                         Actors  Year  \
Title                                                                   
Search Party  Adam Pally, T.J. Miller, Thomas Middleditch,Sh...  2014   
Nine Lives    Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...  2016   

              Runtime (Minutes)  Rating  Votes  Revenue (Millions)  Metascore  
Title                                                                          
Search Party                 93     5.6   4881                 NaN       22.0  
Nine Lives                   87     5.3  12435               19.64       11.0

In [155]:
movies_df['Rating']

Title
Guardians of the Galaxy    8.1
Prometheus                 7.0
Split                      7.3
Sing                       7.2
Suicide Squad              6.2
                          ... 
Secret in Their Eyes       6.2
Hostel: Part II            5.5
Step Up 2: The Streets     6.2
Search Party               5.6
Nine Lives                 5.3
Name: Rating, Length: 1000, dtype: float64

In [66]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, Guardians of the Galaxy to Nine Lives
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Rank                1000 non-null   int64  
 1   Genre               1000 non-null   object 
 2   Description         1000 non-null   object 
 3   Director            1000 non-null   object 
 4   Actors              1000 non-null   object 
 5   Year                1000 non-null   int64  
 6   Runtime (Minutes)   1000 non-null   int64  
 7   Rating              1000 non-null   float64
 8   Votes               1000 non-null   int64  
 9   Revenue (Millions)  872 non-null    float64
 10  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(4)
memory usage: 93.8+ KB


In [156]:
movies_df.shape

(1000, 11)

In [162]:
a1 = {'a':'lavi', 'b':'ml'}
a2 = {'a':'trainer', 'b':'course'}

In [166]:
new_d = {}
for key,value in a1.items():
    print (key,value)
    if key == a2[key]:
        
    

a lavi
b ml


In [68]:
temp_df = movies_df.append(movies_df)  # make a new copy

temp_df.drop_duplicates(inplace=True, keep=False)

temp_df.shape

(0, 11)

In [69]:
movies_df.rename(columns={
        'Runtime (Minutes)': 'Runtime', 
        'Revenue (Millions)': 'Revenue_millions'
    }, inplace=True)


movies_df.columns

Index(['Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year', 'Runtime',
       'Rating', 'Votes', 'Revenue_millions', 'Metascore'],
      dtype='object')

In [70]:
movies_df.columns = [col.lower() for col in movies_df]

movies_df.columns

Index(['rank', 'genre', 'description', 'director', 'actors', 'year', 'runtime',
       'rating', 'votes', 'revenue_millions', 'metascore'],
      dtype='object')

In [71]:
movies_df.isnull().sum()

rank                  0
genre                 0
description           0
director              0
actors                0
year                  0
runtime               0
rating                0
votes                 0
revenue_millions    128
metascore            64
dtype: int64

In [72]:
movies_df.describe()

rank         year      runtime       rating         votes  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1.000000e+03   
mean    500.500000  2012.783000   113.172000     6.723200  1.698083e+05   
std     288.819436     3.205962    18.810908     0.945429  1.887626e+05   
min       1.000000  2006.000000    66.000000     1.900000  6.100000e+01   
25%     250.750000  2010.000000   100.000000     6.200000  3.630900e+04   
50%     500.500000  2014.000000   111.000000     6.800000  1.107990e+05   
75%     750.250000  2016.000000   123.000000     7.400000  2.399098e+05   
max    1000.000000  2016.000000   191.000000     9.000000  1.791916e+06   

       revenue_millions   metascore  
count        872.000000  936.000000  
mean          82.956376   58.985043  
std          103.253540   17.194757  
min            0.000000   11.000000  
25%           13.270000   47.000000  
50%           47.985000   59.500000  
75%          113.715000   72.000000  
max          936.630000  100.000000

In [73]:
movies_df['genre'].describe()

count                        1000
unique                        207
top       Action,Adventure,Sci-Fi
freq                           50
Name: genre, dtype: object

In [74]:
movies_df['genre'].value_counts().head(10)1

Action,Adventure,Sci-Fi       50
Drama                         48
Comedy,Drama,Romance          35
Comedy                        32
Drama,Romance                 31
Comedy,Drama                  27
Animation,Adventure,Comedy    27
Action,Adventure,Fantasy      27
Comedy,Romance                26
Crime,Drama,Thriller          24
Name: genre, dtype: int64

In [75]:
movies_df.corr()

rank      year   runtime    rating     votes  \
rank              1.000000 -0.261605 -0.221739 -0.219555 -0.283876   
year             -0.261605  1.000000 -0.164900 -0.211219 -0.411904   
runtime          -0.221739 -0.164900  1.000000  0.392214  0.407062   
rating           -0.219555 -0.211219  0.392214  1.000000  0.511537   
votes            -0.283876 -0.411904  0.407062  0.511537  1.000000   
revenue_millions -0.271592 -0.126790  0.267953  0.217654  0.639661   
metascore        -0.191869 -0.079305  0.211978  0.631897  0.325684   

                  revenue_millions  metascore  
rank                     -0.271592  -0.191869  
year                     -0.126790  -0.079305  
runtime                   0.267953   0.211978  
rating                    0.217654   0.631897  
votes                     0.639661   0.325684  
revenue_millions          1.000000   0.142397  
metascore                 0.142397   1.000000